# K-IUM 2023. Code to evaluate participants' output.csv
# This script reports the AUROC regarding the presence of intracranial aneurysms
# and the overall accuracy (per location analysis).
# The required files:
#   (1) groundtruth.csv // will be used as a gold standard.
#   (2) output.csv // should be generated by the participants' model prior to running the script
# Note: omitted error handling for brevity.
# Hwangbo, Lee, MD. June 2023.
#
import pandas
from sklearn.metrics import roc_auc_score, f1_score, recall_score


def my_read_csv(filename):
    data = pandas.read_csv(filename)
    aneurysm = data.Aneurysm
    tot = data.drop(columns=['Index'])
    location = data.drop(columns=['Index', 'Aneurysm'])
    tot['Aneurysm'] = (tot['Aneurysm'] > 0.5).astype(int)
    return aneurysm, location, tot


def calc_accuracy(gt_location, output_location):
    confusion_tab = gt_location.subtract(output_location, axis='index', fill_value=0)
    confusion_tab = confusion_tab.abs()
    sum = confusion_tab.sum().sum()
    nrow, ncol = confusion_tab.shape
    total_elem = nrow * ncol
    a = 1.0 - (sum/total_elem)
    return a


def eval_model():
    gt_aneurysm, gt_location, gt_total = my_read_csv('/home/edlab/sjim/k-ium-coding-vessels/test_set/groundtruth.csv')
    output_aneurysm, output_location, output_total = my_read_csv('./results/output2.csv')
    auc_val = roc_auc_score(gt_aneurysm, output_aneurysm)
    acc_val = calc_accuracy(gt_location, output_location)
    
    macro_f1 = f1_score(gt_total, output_total, average='macro', zero_division=0)
    micro_f1 = f1_score(gt_total, output_total, average='micro', zero_division=0)
    macro_recall = recall_score(gt_total, output_total, average='macro', zero_division=0)

    
    return auc_val, acc_val, macro_f1, micro_f1, macro_recall
    # You may use evalute() if you need to evaluate your model


def main():
    auc, acc, macro_f1, micro_f1, recall = eval_model()
    print('AUROC of the provided model')
    print (auc)
    print('Accuracy for locations')
    print (acc)
    print('Macro F1 Score')
    print(macro_f1)
    print('Micro F1 Score')
    print(micro_f1)
    print('Recall Score')
    print(recall)


if __name__ == '__main__':
    main()